### ISSUE TITLE
你好 我这边编译后保存的图片 是花屏 怎么解决啊？

### ISSUE THREAD

**Issue by jayjd** [ClnViewer/Android-fast-screen-capture#1]

**Comment by jayjd** [comment]
我用得安卓版本是 7.1.2
@ClnViewer

**Comment by ClnViewer** [comment]
No image attached from you, sorry
Look this as working example https://github.com/ClnViewer/ADB-Android-Viewer/raw/master/docs/dist/Android-ADB-Viewer.msi

If run from device: `adb.exe shell /data/local/tmp/ascreencap --ratio 2 -f OutBmp.bmp`. 
Else, get saved image from device: `adb.exe pull /data/local/tmp/OutBmp.bmp C:/...file.bmp`
